### ISSUE TITLE
knative/net-istio should support mesh mode for e2e?

### ISSUE THREAD

**Issue by nak3** [knative-sandbox/net-istio#136] opened 2020-06-07 07:49 UTC
There are istio mesh mode specific in knative/serving like:

- TestProbeWhitelist
- ~~TestClusterLocalAuthorization~~
- TestServiceToServiceCall (with injection)
- ~~TestSvcToKubeSvc (trying to add https://github.com/knative/serving/pull/7670)~~

Although these tests should move to knative/net-istio instead of hosting in knative/serving, currently knative/net-istio seems not have the option to run tests with mesh mode.

**Comment by tcnghia** [comment] 2020-08-08 02:56
This is a good idea. Let's do it next milestone.

**Comment by tcnghia** [comment] 2020-12-18 02:35
@arturenault  I think https://github.com/knative-sandbox/net-istio/issues/461 is a duplicate of this

**Closed** 2021-01-27 00:36 UTC
